const ERROR_MESSAGES = {
    INVALID_RIDER: "INVALID_RIDER",
    NO_DRIVERS_AVAILABLE: "NO_DRIVERS_AVAILABLE",
    DRIVERS_MATCHED: "DRIVERS_MATCHED",
    INVALID_RIDE: "INVALID_RIDE",
    RIDE_NOT_COMPLETED: "RIDE_NOT_COMPLETED",
    RIDE_STARTED: "RIDE_STARTED",
    RIDE_STOPPED: "RIDE_STOPPED",
};

const RIDE_STATUS = {
    ACTIVE: "active",
    COMPLETED: "completed",
};

const DISTANCE_THRESHOLD = 5;
const MAX_MATCHED_DRIVERS = 5;
const DECIMAL_PLACES = 2

module.exports = {
    ERROR_MESSAGES,
    RIDE_STATUS,
    DISTANCE_THRESHOLD,
    MAX_MATCHED_DRIVERS,
    DECIMAL_PLACES
};
